name: Generate Snake Animation

on:
  schedule:
    # Jalankan setiap 12 jam
    - cron: "0 */12 * * *"
  workflow_dispatch: 


permissions:
  contents: write

jobs:
  build:
    name: Generate GitHub contribution snake
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout repository
        uses: actions/checkout@v4

   
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Kornelius1
          output: dist/github-contribution-grid-snake.svg

 
      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
